language: node_js
node_js:
  - "8"
before_script:
  - "cd build && \
    npm install && \
    npm install eslint && \
    npm install vows && \
    cd .."
script:
  - "cd build && \
    eslint index.js && \
    cd .."
deploy:
  provider: heroku
  api_key:
    secure: Cpd+HEeQzkArYzEOy6qDDMvpGqdb6EWsg/OYPerwsGgRGhVcHACorndEHOLFA9E+8MPEN45RPMPBQPZUZnetSrLkICSEnqDZtJ8WjWQeqEYepw0v/A+7VmaWHx7EQWiQ/RMFGvosdY2Egvgzq+NQAZOLPDZb7YDHihJOHIM4OcWEgdi7qcOBFZ/o3iskH1Q0PJdJw7ERAP18BqwaKGuVqBLMA9Lteho+z2R2GIsYq2SJg4R9SqpmCBqnAV8do8xnlMhwTyKaIgYAyn2fOHSNu+wfro8SKTh+YHfF9m3nLioIv0UOdBKzJok2RqsyD+yPBgpkLgZ1sF8Fio+BP3BSuERp53RsVh14614nC3m1SDJC6hkimYAwubgXvf7mgtVBInFDqRO63TbYVtdnb/ghnxImvEy4AoCdq3VWjxj2s0mnSDHa/i1K8N2KhUoMXpoCMbwlM6bqHfSBo4CZegIEzwEe31AmU02kUsPSyAqSskLydS8E1X7H3j/64bDqB2i8ClqcsimKCgJXgktxBK2VS/bydr9NNZXqcD9jeHMFHQt8fVXlGno3J3iVHrDnY/Cbes3B5Tly0XQkF2hcBidpYpdPyApA9VdA+rLsM4PddpNIldby5NkUAFY7V56dBvGvfNFXBkWbXUoDsiN63004rOog1h4xR1qdb5dzEU9FHmI=
  app:
    master: mek-graphql
  on:
    repo: maikokitchon/graphql
